-- CONFIG --
-- Remove the (--) For models to be white listed 
-- Add (--) to make them none whitlisted
-- Blacklisted vehicle models
carblacklist = {
--Boats
--	"dinghy",
--	"dinghy2",
--	"dinghy3",
	"dinghy4",
--	"jetmax",
	"marquis",
--	"seadhark",
--	"seadhark2",
--	"seadhark3",
--	"speeder",
--	"speeder2",
--	"squalo",
--	"submersible",
--	"submersible2",
--	"suntrap",
--	"toro",
--	"toro2",
--	"tropic",
--	"tropic2",
	"tug",			--Add(--) for esx server
--Commercails
--	"benson",
--	"biff",
-- 	"hauler",
	"hauler2",
--	"mule",
--	"mule2",
--	"mule3",
--	"packer",
--	"phantom",
	"phantom2",
--	"phantom3",
--	"pounder",
--	"stockade",		--Add(--) for esx Server	
	"stockade3",
	"cerberus",
	"cerberus2",
	"cerberus3",
	"terbyte",
--Compacts
--	"blista",
--	"blista2",
--	"blista3",
--	"brioso",
--	"dilettante",
--	"dilettante2",
--	"lssi2",
--	"panto",
--	"prairie",
--	"rhapsody",
    "issi6",
--Coupes
--	"cogcabrio",
--	"exemplar",
--	"f620",
--	"felon",
--	"felon2",
--	"jackal",
--	"oracle",
--	"oracle2",
--	"sentinel",
--	"sentinel2",
--	"windsor",
--	"windsor2",
--	"zion",
--	"zion2",
--Cycles
--	"bmx",
--	"cruiser",
--	"fixer",
--	"scorcher",
--	"tribike",
--	"tribike2",
--	"tribike3",
--Emergancy
--	"ambulance",
--	"fbi",
--	"fbi2",
--	"firetruck",
--	"pbus",
--	"police",
--	"police2",
--	"police3",
--	"police4",
	"policeold1",
	"policeold2",
--	"policet",
--	"policeb",
--	"polmav",
--	"pranger",
--	"predator",
--	"riot",
--	"sheriff",
--	"sheriff2",
--Helicopters
	"annihilator",
	"buzzard",
	"buzzard2",
--	"frogger",
--	"frogger2",
--	"maverick",
--  "havok",
	"savage",
--	"maverick",
	"savage",
	"skylift",
--	"supervolito",
--	"supervolito2"
--	"seasparrow",
--	"swift",
--	"swift2",
	"valkrie",
	"valkrie2",
--	"volatus"
--industrial
	"bulldozer",
	"cutter",
	"dump",
--	"flatbed",
--	"guardian",
	"handler",
	"mixer",
	"mixer2",
	"rubble",
	"tiptruck",
--	"tiptruck2",
--Military
	"apc",				
	"barracks",
	"barracks2",
	--"barracks3",
	"crusader",
	"halftrack",
	"rhino",
	"trailersmall2",
	"scarab",
	"scarab2",
	"scarab3",

--Motorcycles
--	"akuma",
--	"avarus",
--	"bagger",
--	"bati2",
--	"bati",
--	"bf400",
--	"blazer4",
--	"carbonrs",
--	"chimera",
--	"cliffhanger",
--	"daemon2",
--	"daemon",
--	"defiler",
--	"double",
--	"enduro",
--	"esskey",
--	"faggio",
--	"faggio2",
--	"faggio3",
--	"fcr2",
--	"fcr",
--	"gargoyle",
--	"hakuchou",
--	"hakuchou2",
--	"hexer",
--	"innovation",
--	"lectro",
--	"manchez",
--	"nemesis",
--	"nightblade",
	"oppressor",
	"oppressor2",
--	"pcj",
--	"ratbike",
--	"ruffian",
--	"sanchez",
--	"sanchez2",
--	"sanctus",
	"shotaro",
--	"sovereign",
	"thrust",
--	"vader",
	"vindicator",
--	"vortex",
--	"wolfsbane",
--	"zombiea",
--	"zombieab",
	"deathbike",
	"deathbike2",
	"deathbik3",
--Muscle
--	"blade",
--	"buccaneer",
--	"buccaneer2",
--	"chino",
--	"chino2",
--	"dominator",
--	"dominator2",
--	"dukes",
	"dukes2",
--	"faction",
--	"faction2",
--	"faction3",
--	"gauntlet",
--	"gauntlet2",
--	"hotknife",
--	"lurcher",
--	"moonbeam",
--	"moonbeam2",
--	"nightshade",
--	"phoenix",
--	"picador",
--	"ratloader",
--	"ratloader2",
--	"ruiner",
	"ruiner2",
	"ruiner3",
--	"sabregt",
--	"sabregt2",
--	"sadler2",
--	"slamvan",
--	"slamvan2",
--	"slamvan3",
--	"stalion",
--	"stalion2",
--	"tampa",
--	"tampa3",
--	"vigero",
--	"virgo",
--	"virgo2",
--	"virgo3",
--	"voodoo",
--	"voodoo2",
--Off-Road
--	"bfinjection",
--	"bifta",
--	"blazer",
--	"blazer2",
--	"blazer3",
--	"blazer5",
--	"badhi2",
--	"brawler",
--	"dloader",
--	"dune",
	"dune2",
	"dune3",
	"dune4",
	"dune5",
	"insurgent",
	"insurgent2",
	"insurgent3",
--	"kalahari",
	"lguard",
	"marshall",
--	"mesa",
--	"mesa2",
--	"mesa3",
	"monster",
	"nightshark",
--	"rancherxl",
	"rancherxl2",
--	"rebel",
--	"rebel2",
--	"sandking",
--	"sandking2",
	"technical",
	"technical2",
	"technical3",
--	"trophytruck",
	"trophytruck2",
	"rcbandito",
	"monster5",
	"monster4",
	"monster3",
	"menacer",
	"kalahari",
	"brutus3",
	"brutus2",
	"brusier3",
	"bruiser2",
	"brusier",
	"blazer5",
	"dominator6",
	"dominator5",
	"dominator4",
	"",
	"",

--Planes
--	"besra",
--	"blimp",
	"blimp2",
	"blimp3",
	"cargoplane",
--	"Cuban800",
--	"dodo",
--	"duster",
	"hydra",
	"jet",
	"lazer",
--	"luxor",
--	"luxor2",
--	"mammatus",
--	"miljet",
--	"nimbus",
	"shamai",
--	"stunt",
	"titan",
--	"velum",
--	"velum2",
--	"vestra",
--	"shamal",
--	"nokota",
	"avenger",
--	"microlight",
--	"howard",
--	"avenger2",
--  "mogul",
--  "molotok",
--  "pyro",
--  "seabreeze",
--  "velum",
--  "velum2",
--  "vestra",
--  "volatol"

--SUVs
--	"bjxl",
--	"baller",
--	"baller2",
--	"baller3",
--	"baller4",
	"baller5",
	"baller6",
--	"cavaicade",
--	"cavaicade2",
--	"contender",
--	"dubsta",
--	"dubsta2",
--	"dubsta3",
--	"fq2",
--	"granger",
--	"gresley",
--	"habanero",
--	"huntley",
--	"landstalker",
--	"patroit",
--	"radi",
--	"racoto",
--	"seminole",
--	"serrano",
--	"xls",
	"xls2",
	"mesa2",
--Sedans
--	"asea",
	"asea2",
--	"asterope",
--	"cog55",
--	"cog552",
--	"cognoscenti",
--	"cognoscenti2",
--	"emperor",
--	"emperor2",
--	"emperor3",
--	"fugitive",
--	"glendale",
--	"ingot",
--	"intruder",
	"limo2",
--	"premier",
--	"primo",
--	"primo2",
--	"regina",
--	"romero",
--	"stanier",
--	"stratum",
--	"stretch",
--	"surge",
--	"tailgater",
--	"warrener",
--	"washington",
--Service
	"airbus",
	"brickade",
--	"bus",
	"coach",
--	"rallytruck",
	"rentalbus",
--	"taxi",
	"tourbus",
--	"trash",
--	"trash2",
	"pbus2",
	"airbus",
--Sports
--	"alpha",
--	"banshee",
--	"banshee2",
--	"bestiagts",
--	"buffalo",
--	"buffalo2",
--	"buffalo3",
--	"carbonizzare",
--	"comet2",
--	"comet3",
--	"coquette",
--	"elegy",
--	"elegy2",
--	"feltzer2",
--	"feltzer3",
--	"furoregt",
--	"fusilade",
--	"futo",
--	"infernus2",
--	"jester",
--	"jester2",
--	"khamelion",
--	"kuruma",
	"kuruma2",
--	"lynx",
--	"massacro",
--	"massacro2",
--	"ninef",
--	"ninef2",
--	"omnis",
--	"penumbra",
--	"rapidgt",
--	"rapidgt2",
--	"raptor",
--	"ruston",
--	"schafter2",
--	"schafter3",
--	"schafter4",
	"schafter5",
	"schafter6",
--	"schwarzer",
--	"seven70",
--	"specter",
--	"specter2",
--	"sultan",
--	"surano",
--	"tampa2",
--	"tropos",
--	"verlierer2",
--SportsClassic
	"ardet",
--	"btype",
--	"btype2",
--	"btype3",
--	"casco",
--	"cheeta2",
--	"coquette2",
--	"coquette3",
	"deluxo",
--	"jb700",
--	"mamba",
--	"manana",
--	"monroe",
--	"peyote",
--	"pigalle",
--	"stringer",
--	"stringergt",
	"stromberg",
--	"torero",
--	"tornado",
--	"tornado2",
--	"tornado3",
--	"tornado4",
--	"tornado5",
--	"tornado6",
--	"ztype",
--Super
--	"adder",
--	"bullet",
--	"cheetah",
--	"entityxf",
--	"fmj",
--	"gp1",
--	"infernus",
--	"re7b",
--	"nero",
--	"nero2",
--	"osiris",
--	"penetrator",
--	"pfister811",
--	"prototipo",
--	"reaper",
--	"sheava",
--	"sultanrs",
--	"superd",
--	"t20",
--	"tempesta",
--	"turismo2",
--	"turismor",
--	"tyrus",
--	"vacca",
--	"vagner",
--	"voltic",
	"voltic2",
--	"zentorno",
--	"Italigtb",
--	"Italigtb2,
--	"xa21",
	"scramjet",
	"zr3803",
	"zr3802",
	"zr380",
	"",
	"",
	"",
--Trailers
--	"armytanker",
--	"armytrailer",
--	"armytrailer2",
--	"baletrailer",
--	"boattrailer",
	"cablecar",
--	"docktrailer",
--	"graintrailer",
	"proptrailer",
--	"raketrailer",
--	"tr2",
--	"tr3",
--	"tr4",
--	"trflat",
--	"tvtrailer",
--	"tanker",
--	"tanker2",
--	"trailerlogs",
--	"trailersmall",
--	"trailers",
--	"trailers2",
--	"trailers3",
--Trains
	"freight",
	"freightcar",
	"freightcont1",
	"freightcont2",
	"freightgrain",
	"freighttrailer",
	"tankercar",
	"freightcar",
	"metrotrain",
--Utility
	"Airtug",
--	"caddy",
	"caddy2",
	"caddy3",
	"docktug",
	"forklift",
--	"mower",
	"ripley",
	"sadler",
	"scrap",
--	"towtruck",
	"towtruck2",
	"tractor",
--	"tractor2",
--	"tractor3",
--	"trailerlarge",
--	"trailers4",
	"utillitruck",
	"utillitruck2",
	"utillitruck3",
	"tractor3",
	"trailersmall",
	"rakertrailer",
	"boattrailer",
	"baletrailer",
	"tanker2",
	"tanker",
	"trailerlogs",
	"trailerlarge",
	"freighttrailer",
	"armytrailer",
	"armytrailer2",
	"sadler2",


--Vans
--	"bison",
--	"bison2",
--	"bison3",
--	"bobcatxl",
--	"boxville",
--	"boxville2",
--	"boxville3",
--	"boxville4",
	"boxville5",
--	"burrito",
--	"burrito2",
--	"burrito3",
--	"burrito4",
	"burrito5",
--	"camper",
--	"gburrito",
--	"gburrito2",
	"journey",
--	"minivan",
--	"minivan2",
--	"paradise",
--	"pony",
--	"pony2",
--	"rumpo",
--	"rumpo2",
	"rumpo3",
--	"speedo",
--	"speedo2",
--	"surfer",
--	"surfer2",
--	"taco",
--	"youga",
--	"youga2",
--dlcingame 
	"revolter",
	"tampa3",
	"comet4",
	"viseris",
	"caracara",
	"vigilante",
	"halftrack",
	"khanjali",
	"havok",
	"akula",
	"hunter",
	"thruster",
	"tula",
	"valkyrie",
	"valkyrie2",
	"pyro",
	"mogul",
	"volatol",
	"bombushka",
	"nlkota",
	"savestra",
	"chernobog",
	"barrage",
	"molotok",
	"rogue",
	"seabreeze",
	"starling",
	"ultralight",
	"cognoscenti2",
}

-- CODE --
whitelisted = nil
AddEventHandler('playerSpawned', function(spawn)
    TriggerServerEvent('white')
end)
RegisterNetEvent('checkwhitelist')
AddEventHandler('checkwhitelist', function(whitelist)

print(whitelisted)
whitelisted = whitelist
print('checked')



	end)

Citizen.CreateThread(function()
	while true do
		Wait(1)
		if IsPedInAnyVehicle(GetPlayerPed(-1)) then
		v = GetVehiclePedIsIn(playerPed, false)
		end
		playerPed = GetPlayerPed(-1)
		if whitelisted == nil and playerPed and v then
		if GetPedInVehicleSeat(v, -1) == playerPed then
			checkCar(GetVehiclePedIsIn(playerPed, false))

			end
		end
	end
end)
function checkCar(car)
	if car then
		carModel = GetEntityModel(car)
		carName = GetDisplayNameFromVehicleModel(carModel)

		if isCarBlacklisted(carModel) then
			_DeleteEntity(car)
			sendForbiddenMessage("This vehicle is blacklisted!")
		end
	end
end

function isCarBlacklisted(model)
	for _, blacklistedCar in pairs(carblacklist) do
		if model == GetHashKey(blacklistedCar) then
			return true
		end
	end

	return false
end
